### ISSUE TITLE
homebridge-verisure is taking a long time to load and preventing Homebridge from starting

### ISSUE THREAD

**Issue by hoefs** [ptz0n/homebridge-verisure#100]
Last night the docker homebridge was updated to 1.30 and restarted. Since then I get this message and homebridge will not start.

[2/20/2021, 10:07:34 AM] [Verisure] homebridge-verisure is taking a long time to load and preventing Homebridge from starting.

Everythingwas working fine before. Has something changed or not been adapted in your code? When enabling debug, I don't see more info in the logs...

//EDIT: when disabling homebridge-verisure, homebridge starts with no issues...

**Comment by ptz0n** [comment]
Thanks for submitting, I haven't seen this issue before.

- Which version of Homebridge did you have before updating?
- Do Homebridge start with the plugin if you downgrade to the previously used version?

**Comment by hoefs** [comment]
> Thanks for submitting, I haven't seen this issue before.
> 
> * Which version of Homebridge did you have before updating?

I am always running the latest https://github.com/oznu/docker-homebridge (auto upgraded via docker watchtower)

> * Do Homebridge start with the plugin if you downgrade to the previously used version?

I am unsure on how I can downgrade homebridge with this docker config... It was working fine the day before the upgrade...

These are all my installed plugins (homebridge-nut stopped working, but it was abandoned a long time ago)

<img width="1665" alt="Schermafbeelding 2021-02-21 om 10 02 36" src="https://user-images.githubusercontent.com/7440522/108620358-ffdcac80-742b-11eb-8bce-058c8be97f9f.png">

All the other plugins kept working and connect to internet services (like tahoma etc...)

**Comment by hoefs** [comment]
I uninstalled and reinstalled the plugin and for some reason it is working again...
Saw something from a deprecated version, but it is running fine.

Very strange... Do we need to look into it further?

**Comment by ptz0n** [comment]
Thanks for getting back! I’ll have a go to replicate with the new Homebridge version.

**Comment by hoefs** [comment]
> Thanks for getting back! I’ll have a go to replicate with the new Homebridge version.

And try with installing homebridge-nut... these 2 plugins seems to be conflicting

**Comment by fastenspy** [comment]
Same problem with the new version of the plugin ! I try to reinstall this.

**Comment by hoefs** [comment]
> Same problem with the new version of the plugin ! I try to reinstall this.
> 
> Always same problem after reinstall! `[26/02/2021, 17:51:21] [verisure] homebridge-verisure is taking a long time to load and preventing Homebridge from starting.`

The problem with my install was homebridge-nut preventing homebridge-verisure from starting

**Comment by fastenspy** [comment]
> > Same problem with the new version of the plugin ! I try to reinstall this.
> > Always same problem after reinstall! `[26/02/2021, 17:51:21] [verisure] homebridge-verisure is taking a long time to load and preventing Homebridge from starting.`
> 
> The problem with my install was homebridge-nut preventing homebridge-verisure from starting

Thanks. But I don't have the "Nut" plugin. When I deactivate verisure plugin, now homebridge start !

**Comment by ptz0n** [comment]
Please have a go with `v1.13.1`, this will hopefully give us an actionable error.

**Comment by fastenspy** [comment]
Thanks but I have this:

`[27/02/2021, 16:47:57] [verisure] TypeError: Cannot read property 'split' of undefined
(node:6962) UnhandledPromiseRejectionWarning: TypeError: accessories.forEach is not a function
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:520:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/lib/node_modules/homebridge-verisure/lib/platform.js:102:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by hoefs** [comment]
> Please have a go with `v1.13.1`, this will hopefully give us an actionable error.

#101

**Comment by fastenspy** [comment]
Hello, this is the new version 1.13.1! Now I have this error:


> Thanks. Sorry but I have this:
> 
> `[27/02/2021, 16:47:57] [verisure] TypeError: Cannot read property 'split' of undefined (node:6962) UnhandledPromiseRejectionWarning: TypeError: accessories.forEach is not a function at /usr/lib/node_modules/homebridge/src/bridgeService.ts:520:21 at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18 at /usr/lib/node_modules/homebridge-verisure/lib/platform.js:102:9 at processTicksAndRejections (internal/process/task_queues.js:93:5) (Use `node --trace-warnings ...`to show where the warning was created) (node:6962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:6962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ptz0n** [comment]
With the current logic, this happens if Verisure returns a status HTTP <300, without a valid set-cookie header (including `vid=`) when authenticating.

Working on a fix for the platform to not hinder or delaying starting.

**Comment by fastenspy** [comment]
Perfect! Take your time...

**Comment by ptz0n** [comment]
This issue should be resolved with the latest version; `1.13.2`. Let's keep discussing the auth issue in #101.
