### ISSUE TITLE
Error with latest 1.13.0 + 1.13.1 + 1.13.2 - FIX!!! Disable 2-step verification

### ISSUE THREAD

**Issue by hoefs** [ptz0n/homebridge-verisure#101]
> > Same problem with the new version of the plugin ! I try to reinstall this.
> > Always same problem after reinstall! `[26/02/2021, 17:51:21] [verisure] homebridge-verisure is taking a long time to load and preventing Homebridge from starting.`
> 
> The problem with my install was homebridge-nut preventing homebridge-verisure from starting

Thanks. But I don't have the "Nut" plugin. When I deactivate verisure plugin, now homebridge start !

_Originally posted by @fastenspy in https://github.com/ptz0n/homebridge-verisure/issues/100#issuecomment-787029873_

```
New version of plugin trows error:
[2/27/2021, 8:37:21 AM] [ZP] error: unhandled rejection: TypeError: Cannot read property 'data' of undefined
    at /homebridge/node_modules/homebridge-verisure/lib/platform.js:101:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Homebridge is not starting with verion:
Reverted to previous (CMD: npm install --save homebridge-verisure@1.12.1) and still not working:

```
[2/27/2021, 8:40:47 AM] [Verisure] Error: TypeError: Cannot read property 'split' of undefined
    at /homebridge/node_modules/homebridge-verisure/lib/platform.js:89:72
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/27/2021, 8:40:47 AM] [ZP] error: unhandled rejection: TypeError: accessories.forEach is not a function
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:520:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-verisure/lib/platform.js:102:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by ptz0n** [comment]
Thanks for submitting. Need to take another stab at this tonight 👍🏼

Which node version are you running?

**Comment by hoefs** [comment]
> Thanks for submitting. Need to take another stab at this tonight 👍🏼
> 
> Which node version are you running?

I use the official docker homebridge and use everything what is included

![image](https://user-images.githubusercontent.com/7440522/109383568-83dcdb80-78e7-11eb-8c65-c92e278e9d3f.png)

**Comment by fastenspy** [comment]
Hello, I use Homebridge v1.3.1 on RPI3 with Homebridge UI v4.39.1

Node & NPM:

<img width="453" alt="Capture d’écran 2021-02-27 à 10 55 24" src="https://user-images.githubusercontent.com/14542142/109384037-8e4ca480-78ea-11eb-8ba8-1d4c4dc03c6a.png">

**Comment by hoefs** [comment]
Tried running as child but got same looking error:
```
(node:4226) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /homebridge/node_modules/homebridge-verisure/lib/platform.js:101:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hoefs** [comment]
@ptz0n same issue with 1.13.1

```
[2/27/2021, 11:41:31 PM] [Verisure] TypeError: Cannot read property 'split' of undefined
[2/27/2021, 11:41:31 PM] [ZP] error: unhandled rejection: TypeError: accessories.forEach is not a function
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:520:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-verisure/lib/platform.js:102:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Running as child:
```
[2/27/2021, 11:44:41 PM] [Verisure] TypeError: Cannot read property 'split' of undefined
(node:6023) UnhandledPromiseRejectionWarning: TypeError: accessories.forEach is not a function
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:520:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-verisure/lib/platform.js:102:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ptz0n** [comment]
With the latest version, `1.13.2`, you should get more specific error output. Please share your log output to help the investigation.

```bash
[2/28/2021, 6:23:56 PM] [Verisure] Initializing verisure platform...
[2/28/2021, 6:23:57 PM] [Verisure] Error: Request failed with status code 401
```

**Comment by hoefs** [comment]
> With the latest version, `1.13.2`, you should get more specific error output. Please share your log output to help the investigation.
> 
> ```shell
> [2/28/2021, 6:23:56 PM] [Verisure] Initializing verisure platform...
> [2/28/2021, 6:23:57 PM] [Verisure] Error: Request failed with status code 401
> ```

`[2/28/2021, 6:37:09 PM] [Verisure] Error: Cookie missing from response: HTTP 200`

**Comment by ptz0n** [comment]
@hoefs Thanks! That exactly what I was looking for. This means that Verisure is not including the cookie in the response for your user.

- In which country are you located? Belgium?
- Are you using any specific Verisure app on your phone?

It might be that the new auth endpoints are not yet supported in your country or for your user. I will dig a bit in other projects using the same API.

**Comment by hoefs** [comment]
> @hoefs Thanks! That exactly what I was looking for. This means that Verisure is not including the cookie in the response for your user.
> 
> * In which country are you located? Belgium?
> * Are you using any specific Verisure app on your phone?
> 
> It might be that the new auth endpoints are not yet supported in your country or for your user. I will dig a bit in other projects using the same API.

-- Correct -> Belgium
-- I am using the same app for iOS for the last 5+ years, nothing has changed for my setup = https://apps.apple.com/be/app/verisure/id423747572?l=nl

On https://mypages.verisure.com/ when I enter my username and password, I now get this:

![verisure](https://user-images.githubusercontent.com/7440522/109430321-07d6b680-7a01-11eb-92bf-5ca6a7ae2b50.png)

Can this be related?

**Comment by ptz0n** [comment]
Interesting! I haven’t seen that one before. Can you describe the next steps in detail?

**Comment by hoefs** [comment]
> Interesting! I haven’t seen that one before. Can you describe the next steps in detail?

I get a text message on my phone with a code and I can enter it and trust the browser. 

Same in the iOS app:
![8A924C1C-E5D6-478F-B5D5-7A74521A26A7](https://user-images.githubusercontent.com/7440522/109435128-2ea0e700-7a19-11eb-9def-0768221d040b.png)

![D3669235-13B1-4E37-ABF0-ABFCB382213D](https://user-images.githubusercontent.com/7440522/109435138-38c2e580-7a19-11eb-9cfa-3ae5eda78e35.png)

Is there an fix for this?

**Comment by fastenspy** [comment]
Hello, with version 1.13.2:

`[01/03/2021, 06:43:48] [verisure] Error: Cookie missing from response: HTTP 200`

I'm live in Belgium too.

**Comment by hoefs** [comment]
@ptz0n disabling 2-step verification fixes the issue:

![verisure2](https://user-images.githubusercontent.com/7440522/109479227-760b8f80-7a7a-11eb-982e-a654ea84514e.png)

![verisure3](https://user-images.githubusercontent.com/7440522/109479245-7a37ad00-7a7a-11eb-9da0-5ab4f421db82.png)

![verisure4](https://user-images.githubusercontent.com/7440522/109479263-7dcb3400-7a7a-11eb-8a1f-db356f466c64.png)

![verisure5](https://user-images.githubusercontent.com/7440522/109479279-81f75180-7a7a-11eb-9075-77d37b04c278.png)

![verisure6](https://user-images.githubusercontent.com/7440522/109479297-858ad880-7a7a-11eb-81d1-3b6cfe29b881.png)

They should keep 2-step verification and work with app specific password. But this is a work-around for now!

Thanks for the support!

**Comment by ptz0n** [comment]
Great that we found a solution! I would really like to support MFA in the future, but that would require Verisure to support for third party code generators or ability to refresh expired tokens/sessions using a refresh token.

**Comment by fastenspy** [comment]
Thanks for the tip. I did it differently ... I created another account with a new email address configured for "basic use". It's better I think, no more two-step verification and it's another alarm code ("home user" for notifications). I find it more secure than the email address for "admin"

**Comment by hoefs** [comment]
> Thanks for the tip. I did it differently ... I created another account with a new email address configured for "basic use". It's better I think, no more two-step verification and it's another alarm code ("home user" for notifications). I find it more secure than the email address for "admin"

@ptz0n I tried this, but I get this:

```
[3/3/2021, 9:51:29 AM] [Verisure] <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

**Comment by oskarhart** [comment]
I have turned off 2 step verification but still get this Error and nothing shows up in homekitt 
[verisure] Error: Cookie missing from response: HTTP 200

**Comment by hoefs** [comment]
> I have turned off 2 step verification but still get this Error and nothing shows up in homekitt
> [verisure] Error: Cookie missing from response: HTTP 200

Sure it is off? Your user has to be an admin. I needed to make my homebridge dedicated user with limited rights an admin to be able to disable 2FA. After this I made it a limited user again.

**Comment by oskarhart** [comment]
I am sure i did turn it off but now I have used another account log inn and its working with it.

**Comment by fastenspy** [comment]
hello, check it out!  at home, Verisure has activated double authentication this week on my new account ! 
![Uploading Image PNG.png…]()

**Comment by oskarhart** [comment]
The account I'm using now has not activated double authentication so I have activated Bridge Settings child bridge to prevent it to stop/slow down rest of homebridge when they decide to activate it

**Comment by ptz0n** [comment]
@fastenspy Verisure is enrolling each market. While we are working on a way to support it, the fix is to disable 2FA.

**Comment by ptz0n** [comment]
@fastenspy Just want to inform you that `v1.14.0` have been released with support for MFA. Have a lovely Wednesday 🎉

**Comment by fastenspy** [comment]
you are the best !  I test this tonight
