### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by tomsteenbakkers** [ptz0n/homebridge-verisure#103]
I just updated Homebridge and after the restart I get the following error.

```
[3/3/2021, 10:22:43 AM] [homebridge-verisure] <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

No other errors but the items are exposed to Homekit. Logging on the Verisure website and app is working fine.

**Comment by ptz0n** [comment]
Interesting, do you get the error once or at random when requesting states and values?

**Comment by tomsteenbakkers** [comment]
I get this error when homebridge is starting/restarting. I also used the new feature to run this plugin in a Child Bridge but no result.

**Comment by hoefs** [comment]
@tomsteenbakkers it started working again here

**Comment by tomsteenbakkers** [comment]
It's working again also when i keep using the Child Bridge config. Maybe there was something wrong with the Verisure services.
