### ISSUE TITLE
2 step authentication

### ISSUE THREAD

**Issue by rbeniers** [ptz0n/homebridge-verisure#104]
Verisure is introducing 2 step authentication.
Will this plug-in also support 2 step authentication, so it still works after Verisure enables this?
Just a heads-up....

**Comment by 1aranzant** [comment]
https://github.com/ptz0n/homebridge-verisure/issues/101

**Comment by ptz0n** [comment]
The plugin does not yet support MFA.

Until then, please have a look at this new section of the readme: [Multi-factor authentication](https://github.com/ptz0n/homebridge-verisure#multi-factor-authentication)

**Comment by ptz0n** [comment]
Let's discuss the feature here: https://github.com/ptz0n/homebridge-verisure/discussions/107

**Comment by ptz0n** [comment]
Just want to inform you that `v1.14.0` have been released with support for MFA. Have a lovely Wednesday 🎉
