### ISSUE TITLE
Support for 2FA

### ISSUE THREAD

**Issue by napthemax** [ptz0n/homebridge-verisure#106]
Guess we all received this email today from Verisure. Don't know if it's an issue – disabling 2FA is an easy thing, but I'd rather have it supported.

-------------

Information to users with a third-party integration to Verisure
--
Our system indicates that you are using a third-party integration to connect to Verisure functionality. If this is not the case, you can ignore this email. Otherwise, please continue reading.
Third-party integrations are not an officially sanctioned way to connect to Verisure. However, we hope that you are happy with the functionality provided through MyPages and Verisure app and will continue to use it. This email contains instructions for how to use third-party integrations together with 2-step verification.
Our goal is to keep our customers safe and secure. This includes maintaining a high security level for your Verisure account and reduce the risk of unauthorized access. In the next couple of weeks, we will therefor introduce 2-step verification for all logins to MyPages and the Verisure app.
Once 2-step verification is enabled for your account, you will need a one-time code in addition to your username and password.

**Comment by ptz0n** [comment]
Yes, I received the email too. Duplicate issues: #104 #105

Without having a closer look at their implementation, I see three paths to supporting MFA:

1. If the session (cookie) have a long TTL, we could provide an interactive cli tool to get the token. Then you can set the token in your config.
2. The new auth flow seem to return a JWT. If they support renewing tokens once expired using the refresh token, that would be awesome. Authenticating as suggested in 1.
3. Support for third party code generators.

**Comment by ptz0n** [comment]
Let's discuss the feature here: https://github.com/ptz0n/homebridge-verisure/discussions/107

**Comment by ptz0n** [comment]
Just released `v1.14.0` with support for MFA. Happy Wednesday 🎉
