### ISSUE TITLE
SMS approval of account

### ISSUE THREAD

**Issue by palletodap** [ptz0n/homebridge-verisure#108]
Just noticed that verisure have optimized the security on there website, and browser/devices now have to be approved over SMS on login.

It seems to have killed the connection between the plugin and verisure? I gets this error: [Verisure] Error: Cookie missing from response: HTTP 200

**Comment by palletodap** [comment]
Sorry, didn't see this already has been closed.

**Comment by ptz0n** [comment]
Just want to inform you that `v1.14.0` have been released with support for MFA. Have a lovely Wednesday 🎉
