### ISSUE TITLE
not showing up in HomeKit 

### ISSUE THREAD

**Issue by oskarhart** [ptz0n/homebridge-verisure#109]
getting this error and nothing shoving up in HomeKit, it was running fine before 2part authentication, and I have now removed it and can't get it to work.
[homebridge-verisure] Error: Cookie missing from response: HTTP 200

**Comment by ptz0n** [comment]
Yes, this is due to the 2FA. Please see this section of the readme: [Multi-factor authentication](https://github.com/ptz0n/homebridge-verisure#multi-factor-authentication)

Additionally we are discussion support for 2FA here: https://github.com/ptz0n/homebridge-verisure/discussions/107

**Comment by ptz0n** [comment]
Just want to inform you that `v1.14.0` have been released with support for MFA. Have a lovely Wednesday 🎉
