### ISSUE TITLE
Yale door man

### ISSUE THREAD

**Issue by FamJohansson** [ptz0n/homebridge-verisure#11]
Can I use this plugin for Yale doorman with Verisure?

**Comment by ptz0n** [comment]
Hi there, that could work. Can you provide the API calls (without auth) to lock & unlock and get status?

**Comment by FamJohansson** [comment]
Should I send you some API calls? How to pull out this?

**Comment by ptz0n** [comment]
You can use a tool like [Charles](http://charlesproxy.com) to analyse the network activity from/to the Verisure app when performing the actions you are missing.

I don't have a Yale lock in my setup to provide the details needed for implementation in this plugin.

**Comment by FamJohansson** [comment]
Is this something you can use? (If I export it)

**Comment by ptz0n** [comment]
Did you attach a file? Nothing shows here on GitHub 😢

**Comment by FamJohansson** [comment]
Do you have en direct email address?

Hilsen
Tore N. Johansson 
Høgtunvegen 9 
6017 Ålesund 
Mobil:+

**Comment by ptz0n** [comment]
Ofc, you can email me at erik@eng.se

**Comment by FamJohansson** [comment]
Then I try to add the files here.. :-)

[verisure.zip](https://github.com/ptz0n/homebridge-verisure/files/994224/verisure.zip)

**Comment by FamJohansson** [comment]
@ptz0n Can you use this?
[Verisure.zip](https://github.com/ptz0n/homebridge-verisure/files/999683/Verisure.zip)

**Comment by wahlly** [comment]
Any updates on this? 🤔

**Comment by FamJohansson** [comment]
I think Erik is working on it.

**Comment by kodsnutten** [comment]
Don't know if you got any messages about it, but I created a fork from this repository and I have implemented some code for Yale Doorman. The code is available [here](https://github.com/kodsnutten/homebridge-verisure).

**Comment by FamJohansson** [comment]
Hello,
Can I then just use this npm install -g homebridge-verisure
To install it?
/Tore 

> Den 19. jun. 2017 kl. 17.13 skrev kodsnutten <notifications@github.com>:
> 
> Don't know if you got any messages about it, but I created a fork from this repository and I have implemented some code for Yale Doorman.

**Comment by kodsnutten** [comment]
> Can I then just use this npm install -g homebridge-verisure
> To install it?
No, unfortunately I'd like to have some development testing on the code - which means that you'd have to "jump some hoops" to get my version onto your system. 
Maybe I could create a "pull request" for @ptz0n so he could merge it from my fork, and release it to NPM,

Otherwise you'd need to replace the index.js file in the homebridge-verisure directory of your device / server.

**Comment by kodsnutten** [comment]
Note that you need to add a new configuration entry (doorcode) as specified in the updated [README.md](https://github.com/kodsnutten/homebridge-verisure/blob/master/README.md). 
I have created a extra user in Verisure, named "Siri"

**Comment by FamJohansson** [comment]
Is Ii only the indx.js file and the doorcode in the configuration file that's needed to be replaced an edit. Then I can fix it

Hilsen

**Comment by ptz0n** [comment]
Nice! Please create a PR 👍🏼

**Comment by FamJohansson** [comment]
Yes please create pull request

**Comment by kulvik** [comment]
Thanks a lot for the Yale Doorman code. However I have another problem. I only get listed 5 units out of my total 15+ units. So the Yale doormans (among other things) are never listed. Either the API is just giving me 5 units, or it's the device type "WATER1" (water detectors) that are not supported and created problems for me :/

Any ideas? Right now I'm getting this output after starting homebridge: 
`[2017-6-26 19:19:25] Loaded plugin: homebridge-verisure
[2017-6-26 19:19:25] Registering platform 'homebridge-verisure.verisure'
[2017-6-26 19:19:25] ---
[2017-6-26 19:19:25] Loaded config.json with 0 accessories and 1 platforms.
[2017-6-26 19:19:25] ---
[2017-6-26 19:19:25] Loading 1 platforms...
[2017-6-26 19:19:25] [Verisure] Initializing verisure platform...
Load homebridge-verisure.verisure
[2017-6-26 19:19:26] [Verisure] Initializing platform accessory 'Rökdetektor (kjellerstue)'...
[2017-6-26 19:19:26] [Verisure] SMOKE2
[2017-6-26 19:19:26] [Verisure] Initializing platform accessory 'Rökdetektor (yttergang)'...
[2017-6-26 19:19:26] [Verisure] SMOKE2
[2017-6-26 19:19:26] [Verisure] Initializing platform accessory 'Vanndetektor (Kjøkken)'...
[2017-6-26 19:19:26] [Verisure] WATER1
[2017-6-26 19:19:26] [Verisure] Initializing platform accessory 'Vanndetektor (Vaskerom kjeller)'...
[2017-6-26 19:19:26] [Verisure] WATER1
[2017-6-26 19:19:26] [Verisure] Initializing platform accessory 'Siren (KJØKKEN)'...
[2017-6-26 19:19:26] [Verisure] SIREN1
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-6-26 19:19:26] Homebridge is running on port 51826.`

**Comment by kodsnutten** [comment]
@kulvik , really don't know exactly what is the problem, but I'm suspecting that maybe you have more than one "installation". I only have my Yale Doorman run through Verisure (all of my other home automation stuff is is managed by [Domoticz](https://domoticz.com/)).

I have created a debug branch which you can use instead. This code gives more information about your installation(s), and the response from the "Overview" which should contain all of your devices.

You can install the debug branch-code with the command
`npm install -g git+https://github.com/kodsnutten/homebridge-verisure#debug`

**Comment by siavashvj** [comment]
First of all, thank you for this. 

However, there is one issue that complicates things and crashes HomeBridge: When you try locking an already locked Yale Doorman, it crashes and provides the error I pasted below (also for the reversed action: unlocking an already unlocked Yale Doorman): 

`Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/index.js:293:11)
    at Request._callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:27:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/request/request.js:1091:12)
`

**Comment by askusbloodfist** [comment]
Should you not Merg these so we have the new code for the door etc on the verisure plugin?

**Comment by ptz0n** [comment]
Merged #13, let's close this one?
