### ISSUE TITLE
Error: cookie missing from response: HTTP 200

### ISSUE THREAD

**Issue by pellehebs** [ptz0n/homebridge-verisure#112]
Hi Guys

Im getting this in my Hoobs log when i try opening the verisure plugin. Worked perfectly a week ago - now its dead. Anybody know whats wrong and know of a fix?

**Comment by ptz0n** [comment]
Thanks for reaching out. This is due to Verisure started enrolling MFA. I’m working on a new version to support the new auth flow.

The quick fix is to disable MFA for your user.

Please see pinned issue #110

**Comment by ptz0n** [comment]
Just want to inform you that `v1.14.0` have been released with support for MFA. Have a lovely Wednesday 🎉
