### ISSUE TITLE
Obtain 2FA token

### ISSUE THREAD

**Issue by bjornand1** [ptz0n/homebridge-verisure#113]
Hi, very happy to see that the plugin should now work with 2FA! However, I couldn't really figure out how to obtain the required token - probably me being stupid, but hope for some help.

**Comment by ptz0n** [comment]
It's great that you are reaching out again! I tried to put clear instructions for how to generate the `token` in the README. Obviously, these could be improved.

1. Install the plugin `$ npm i -g homebridge-verisure`
2. Start the cli tool `$ npx verisure` and follow the steps
3. Copy and paste the values into your config.

To help improve the documentation and guidance for users like yourself:

- What does your setup look like? HOOBS?
- Have you reviewed the README?
- If you did, was the heading "Multi-factor authentication" easy to find?
- How would you like to be guided?

**Comment by bjornand1** [comment]
Excellent, thanks, I will test this tonight.
My setup is Homebridge on a Synology, in Docker, and I read the README section, but what I missed is that the command "$ npx verisure" refers to a tool. I assume this command is run in the terminal section of the Homebridge UI? Sorry, terminal commands are not my strong side!

**Comment by bjornand1** [comment]
Had to try right away, and this worked perfectly! So I believe that for non-experts in terminal usage, what was missing was the explanation that the token is obtained through the terminal commands.
Again, thanks for maintaining this plugin!

**Comment by frodekleven** [comment]
Thanks for fixing the 2FA problem. I've been wondering why I've been having plugin troubles lately!

Like @bjornand1 says, I think specifying that the `$ npx verisure` needs to be entered into Terminal will greatly improve understanding. Also, maybe add this to the release notes shown when you update the plugin?

**Comment by ptz0n** [comment]
Thanks for all the feedback. I've updated the README with the suggested clarification.
