### ISSUE TITLE
Bridged accessory is not reachable

### ISSUE THREAD

**Issue by redjoto** [ptz0n/homebridge-verisure#115]
All the time I get these warning signs for Verisure components in my Eve app. Although they are showing the right values. Is this a known bug?
![FD192B10-2AF1-447D-8D47-D50C7F26F250](https://user-images.githubusercontent.com/79904766/111867140-693fd480-8972-11eb-9716-464088ac9269.jpeg)
![456C4ADD-27BF-43F9-8D0E-537AD941B5BF](https://user-images.githubusercontent.com/79904766/111867141-6cd35b80-8972-11eb-912e-b5668329d0bd.jpeg)
![3F49751B-BC89-4B8F-9498-EC5BF8832951](https://user-images.githubusercontent.com/79904766/111867142-6cd35b80-8972-11eb-8141-6ab875acd9b1.jpeg)

**Comment by ptz0n** [comment]
- Which version of the plugin are you running?
- When did the issue start occuring?
- Do you have the same issue when using the Home app?

**Comment by redjoto** [comment]
> * Which version of the plugin are you running?
> * When did the issue start occuring?
> * Do you have the same issue when using the Home app?

![7E4D4598-4642-4FCF-95C4-921016A4EA3D](https://user-images.githubusercontent.com/79904766/111875729-8341dd00-899b-11eb-9ccc-b47f3ec44e9a.jpeg)

This issue had occured since I started using Homebridge a month ago.

The issue isn’t occuring as often in the Home app as in the Eve app, but it happens now and then.

**Comment by ptz0n** [comment]
I’m guessing this is because of timeouts in the apps. If Homebridge does not respond within a certain time frame, the message shows.

Make sure your Homebridge instance is running on a wired connection to minimize latency.

**Comment by redjoto** [comment]
> I’m guessing this is because of timeouts in the apps. If Homebridge does not respond within a certain time frame, the message shows.
> 
> Make sure your Homebridge instance is running on a wired connection to minimize latency.

But this would generate these issues for the devices from other plugins as well? It’s only the Verisure components that has this issue.

Yes, my Homebridge is running on a wired connection.

**Comment by ptz0n** [comment]
This is a known issue with HomeKit. Some claim they lowered the response time threshold in the latest release too. Cannot do much about Verisure's API latency. Any suggestions?

**Comment by redjoto** [comment]
> This is a known issue with HomeKit. Some claim they lowered the response time threshold in the latest release too. Cannot do much about Verisure's API latency. Any suggestions?

Ah, I see. Guess we have to live with it :-)
