### ISSUE TITLE
Home does not show Yale Doorman or alarm

### ISSUE THREAD

**Issue by Holseker** [ptz0n/homebridge-verisure#116]
Hi,

After the last update and 2 factor login, the alarm and door lock does not longer show in homekit or home app. 
Anyone have any ideas? The plugin is updated and token is in the config as described

**Comment by ptz0n** [comment]
Hi & thanks for reaching out.

What does your Homebridge log look like? Are you sure that that the plugin is initiated correctly with all the expected accessories?

Did you put the alarmCode into your plugin config?

**Comment by Holseker** [comment]
Hi,

The problem was the door and alarm code missing from the config. I just copied the config from the npx verisure command. Sorry for the bother! Thanks allot for the plugin!

**Comment by ptz0n** [comment]
Great!
