### ISSUE TITLE
Smart Camera Support?

### ISSUE THREAD

**Issue by bjornand1** [ptz0n/homebridge-verisure#117]
Hi, I am about to get a couple of the Verisure smart cameras. Is there any way to get these to work with Homebridge?

**Comment by ptz0n** [comment]
This plugin does not yet support IP cameras. Which specific camera hardware are you looking to buy?

**Comment by bjornand1** [comment]
Thanks, I am looking at these: https://www.verisure.no/produkter/smartkamera

**Comment by ptz0n** [comment]
Personally, I wound not buy such old tech. Someone wrote that it was an old Samsung(?) camera rebranded to Verisure when released.

For great IP cameras, you should check out UniFi 🙌🏻

**Comment by bjornand1** [comment]
I wouldn’t either normally, but I get them cheap secondhand to replace even older Verisure cameras that can only take stills if the alarm is triggered

**Comment by ptz0n** [comment]
Sure, then it might be a good idea. I was referring to the current retail price for that old tech.

Regarding getting them into HomeKit, I would try out any of the IP camera plugins first.

**Comment by bjornand1** [comment]
Thanks, I will try that!
