### ISSUE TITLE
Night control, not supported ?

### ISSUE THREAD

**Issue by ghost** [ptz0n/homebridge-verisure#12]
Hello,
It seems that the Night Control equipment (Homepad1) is not yet supported.
Do you think that you can add it ?
Thanks a lot.
Antoine

**Comment by ptz0n** [comment]
Great input, this device is now "supported" and should no longer make your homebridge setup crash.

Is there any features that you want implemented for this device?

**Comment by marcus13371337** [comment]
I still get this error, any fixes?

**Comment by marcus13371337** [comment]
Pull request created!
