### ISSUE TITLE
Support for 2FA

### ISSUE THREAD

**Issue by skPink** [ptz0n/homebridge-verisure#121]
I have new installation but verisure give me only username no email npx verisure don't work with my email address or username and correct password

**Comment by skPink** [comment]
@ptz0n If you can help me thx hi have this error

`UnhandledPromiseRejectionWarning: Error: Request failed with status code 40`

**Comment by ptz0n** [comment]
Which website do you normally use to login?

**Comment by skPink** [comment]
@ptz0n Thx for reply this one : https://customers.securitasdirect.fr/

**Comment by ptz0n** [comment]
This plugin does not support Securitas Direct installations. You should try out this one instead: https://github.com/ptz0n/homebridge-securitas-direct
