### ISSUE TITLE
Cant get mfa to work

### ISSUE THREAD

**Issue by hanses89** [ptz0n/homebridge-verisure#123]
Im trying to get this up and running, but i cant seem to get the mfa to work. after removing the mfa for testing purposes, i can add my smart lock etc without any issue.. 

This is what i get when running npx verisure in terminal:
![image](https://user-images.githubusercontent.com/62284780/130696299-cfa4adbd-96b4-4ab6-98ac-f44af55d9c89.png)

pls help:)

**Comment by ptz0n** [comment]
Hi, you first need to install the module. Run:

npm install verisure

**Comment by hanses89** [comment]
So installing the plug-in itself is not good enough? I did this with hoobs.. so npm install Verisure installs the mfa part of it?

**Comment by ptz0n** [comment]
If you have already unstalled the module locally, then you need to locate it. I’m not sure where hoobs usually put things.

Otherwise, you can use the tool on another machine. It does not have to be the same environment.

**Comment by hanses89** [comment]
Maybe I don’t understand properly… but the npm install Verisure is the same as installing home bridge-Verisure plugin?

because I have only installed the plugin via the library in hoobs so far…

**Comment by ptz0n** [comment]
Sorry, ofc it should be `npm install homebridge-verisure`.

**Comment by hanses89** [comment]
ok. 
so the guide is a bit wrong here then maybe?

it should say this to do the mfa thing right?:
npx homebridge-verisure

**Comment by hanses89** [comment]
I think that did the trick... Is there any way to hide the password and token from the config? I'm a bit new here. so step by step would be much appreciated:)

**Comment by hanses89** [comment]
and lastly... Why does the icon for the lock show as a lock on iphone, and as a sregular switch on ipad?:)

**Comment by ptz0n** [comment]
Sorry for not getting back on your final question there. I'd say it's up to Apple to be consistent. Are you running the same iOS version on both devices?

**Comment by CapitaineFlam1** [comment]
W/re to the "Hoobs x Verisure" setup:
1. ssh into Hoobs
2. Logon (hoobs/hoobsadmin)
3. Run `npx homebridge-verisure`
4. Install the homebridge-verisure package. 
5. Authenticate with Verisure credentials.
6. Receive token and use this in config of plugin in Hoobs.

**Comment by ptz0n** [comment]
Thanks. It seems like `npx` have changed the lookup logic and will require single executables to be named to match the package name. I'll update the README to clarify.
