### ISSUE TITLE
Not an issue - just a thank you!

### ISSUE THREAD

**Issue by Tommigun1980** [ptz0n/homebridge-verisure#124]
Thank you for the best plugin on HomeBridge! Hugely appreciated.

Feel free to close.

**Comment by ptz0n** [comment]
Thanks a lot! ♥️

Do you mind sharing how long you've been using the plugin?

Please consider sponsoring the project: https://www.paypal.com/paypalme/ptz0n

**Comment by Tommigun1980** [comment]
Hi. I'd say around a month by now.
