### ISSUE TITLE
Image request support from motion detector/cam (v2)

### ISSUE THREAD

**Issue by spectrazureus** [ptz0n/homebridge-verisure#129]
This is a feature request. The Homebridge Verisure plugin cannot request images from the motion detector with built-in camera.
However, another project pretends to be able to request images on demand but only with version 1 of the motion detector/cam.
https://github.com/Xav-74/verisure/commit/848f761f104df271ba9f7a081b5f1818205a9d28
$path = "plugins/verisure/data/".date("Ymd_His")."_smartplugID_".init('device').".jpg";	
 	$img = verisure::GetPhotosRequest(init('numinstall'),init('username'),init('pwd'),init('country'),init('device'));
 	$image = base64_decode($img);
 	file_put_contents($path,$image);
Maybe this code extract is probably outdated (no MFA support), but @Xav-74 had the v2 support of these motion detectors/camera in roadmap.

**Comment by spectrazureus** [comment]
@Xav-74 published extensive documentation (sorry in French) here: [https://xav-74.github.io/Documentation/verisure/fr_FR]

**Comment by spectrazureus** [comment]
https://github.com/Cebeerre/SecuritasDirectAPI#photo-requests

**Comment by ptz0n** [comment]
Are you currently using this plugin?

It seems to me that you have a Securitas Direct installation. This plugin is for Vbox installations. Sorry for the confusion. If that's the case, please create an issue here instead:

https://github.com/ptz0n/homebridge-securitas-direct

**Comment by spectrazureus** [comment]
Yes I am using a Verisure alarm system
Will do

**Comment by spectrazureus** [comment]
in the wrong project. deleting

**Comment by spectrazureus** [comment]
not the right project for this enhancement
