### ISSUE TITLE
Cant mfa to work

### ISSUE THREAD

**Issue by hanses89** [ptz0n/homebridge-verisure#130]
Trying to get mfa working to get the one time code.. but i cant do it.. help me pls?

**Comment by ptz0n** [comment]
Hi, please provide some more details.

- Where are you located?
- Are you using email + password?
- How far into the process do you get?

**Comment by hanses89** [comment]
Norway.
I have had this working. but i just changed my password for Verisure and the smart lock stopped working.. I cant remember how i got the token last time....  i might need a new token when changing password? Now i have the new password configured but the old token i guess. it starts with "vid="

**Comment by hanses89** [comment]
i got it working.. had to type npx homebridge-verisure.... not npx verisure:)

**Comment by ptz0n** [comment]
Strange, but great!
