### ISSUE TITLE
Problem with Verisures latest firmware version 38120

### ISSUE THREAD

**Issue by Joystern** [ptz0n/homebridge-verisure#136]
After updating Verisure components firmware to 38120 it doesn’t update correctly in homebridge. It get’s stuck on ”Updating”.

**Comment by ptz0n** [comment]
Interesting. Have you restarted Homebridge? Any details or errors in the log?

Which version of node, homebridge and plugin are you using?

**Comment by Joystern** [comment]
Homebridge looks like it always does. But it just says updating in the home app. 

Tried to restart but same issue. 

Npm v8.1.2
Node v16.13.2
Homebridge v1.3.9 (HAP v0.9.8)
Homebridge-Verisure v1.15.0

**Comment by Joystern** [comment]
Did a whole new setup on another computer and now it works. Don’t know what the issue was but it’s not the firmware apparently.

**Comment by ptz0n** [comment]
Thanks for the update. Still strange behaviour. I have a few ideas to try out.

I’m also thinking of refactoring the platform to which might be more stable.
