### ISSUE TITLE
Multiple homes, different admin accounts

### ISSUE THREAD

**Issue by Toetta** [ptz0n/homebridge-verisure#139]
Hi!

In Homkit I have two different locations. Our house and our family summer house.
Im admin/owner of the account for our house and a relative is owner and admin to the other Verisure account connected to the summer house. Im invited as second admin to the summerhouse  (not owner) in HomeKit and Verisure

In home bridge both homes show but I am not allowed to arrange connected devices in HomeKit to the other site. So the door locks are wrongly stuck in my house which is the default site...

Any workarounds available to sort this?

**Comment by ptz0n** [comment]
Thanks for reaching out. Sounds like you have added both Verisure installations to the same Homebridge instance. If you want to use Verisure installations in different Homes in HomeKit, I believe you need to set them up separately.

**Comment by Toetta** [comment]
Thanks for answering

No, that is not the case. 

I can access the locks for the different homes as should be by having admin rights on both the homes in the verisure app from the two different accounts.

I miss the functionality to seperate the locks into the two different home locations in apple home.

![image](https://user-images.githubusercontent.com/98849926/157594358-106e2226-bf7c-43b8-bd82-f896408a04ef.png)

![image](https://user-images.githubusercontent.com/98849926/157594373-4cc160a2-c583-46cd-8caa-7bcc729200c0.png)

**Comment by ptz0n** [comment]
Do you have two different locations setup in the Home app already? If not, that's the first thing you need to do.

https://www.macrumors.com/how-to/add-a-second-home-to-homekit/

**Comment by Toetta** [comment]
Yes I do, all native homekit devices work on the different seperated homes.

The homebridge yale is not able to seperate them accordingly

Best regards

Malkus



mån 21 mars 2022 kl. 10:13 skrev Erik Eng ***@***.***>:

**Comment by ptz0n** [comment]
Great, now you need to separate the installations into two different homebridge instances. One for each home. You can specify the desired installation in your config using the `installations` property. See README.

**Comment by Toetta** [comment]
Ok!!

Excellent, many thanks. I will try

Cheers

Malkus

mån 21 mars 2022 kl. 10:31 skrev Erik Eng ***@***.***>:
