### ISSUE TITLE
Auto-Lock all of the sudden

### ISSUE THREAD

**Issue by tonijj** [ptz0n/homebridge-verisure#146]
Hi, 

First of all, I've used the plugin for years on an RPI3 and its truly great, kudos to the developer!!

Now, I just updated it to the latest version and for some reason it auto-locks my Yale V2N just seconds after I unlocked it. 

Throgout the years, this has never happened. 

I looked in the Verisure app and nothing has changed - I have a schedule to have Autolock on only between 20.00 to 08.00. 

Sincerely

**Comment by ptz0n** [comment]
Thanks a lot. Happy that you enjoy the plugin. Don't forget to support the project [here](https://www.paypal.com/paypalme/ptz0n).

Interesting issue. The latest version introduce the config property `showAutoLockSwitch`. The default value for this property is `true`. This update should not have caused any change to your setup, if config was untouched.

- What does your config look like? __Please redact all secrets. These should never be shared publicly.__
- What does your Homebridge logs look like when unlocking?
- Is the auto-lock triggered by Homebridge or possibly something else?
