### ISSUE TITLE
Siren not exposed

### ISSUE THREAD

**Issue by FluGanz** [ptz0n/homebridge-verisure#148]
My siren is not exposed, is there any way to fix that, got the siren with the temp sensor in it and i can see the temp but not activate the siren nor the alarm

**Comment by ptz0n** [comment]
Hi & thanks for reaching out. So the siren temperature sensor is exposed and showing up in your Home app?

Security alarm system is exposed once you put the alarm code in your config. Have you done so?

I do not believe there is a way to activate the siren itself via the API or official Verisure app.

**Comment by FluGanz** [comment]
Yes, i have the 4 digit code and the token in my config i have two sirens, one in the garage and one in the house but i cant see anyone of them

**Comment by ptz0n** [comment]
Okej, so you are missing one temperature sensor accessory and the alarm accessory from the list?

What does the two sirens look like?

**Comment by FluGanz** [comment]
I have this one in my garage

**Comment by ptz0n** [comment]
The one in your garage does not have a temperature sensor.

Please check the startup logs to see if the security alarm accessory is created.

**Comment by FluGanz** [comment]
![19B63B7E-94A2-43B2-A35F-A07B7290F98A](https://user-images.githubusercontent.com/77684722/197950117-684f9094-2d64-4213-ab54-79ae575ab5f3.png)

it says indoor siren with heat detection

**Comment by ptz0n** [comment]
By bad, I was mistaken about it not having a temp sensor.

”Röstenhet” is not showing up? Please check the logs.

**Comment by ptz0n** [comment]
Any update?

**Comment by FluGanz** [comment]
![F5897B72-4C91-47A9-A149-55DBED3961C0](https://user-images.githubusercontent.com/77684722/198883354-f7c9b6e4-28e2-464c-bfb1-b44c8aedcaa9.jpeg)

Dont know if this helps? Still only have the tempsensors

**Comment by ptz0n** [comment]
Ok, so Homebridge is successfully initiating the two temperature sensors?

Does the log output include "Alarm .."?
