### ISSUE TITLE
Unable to get installations. Please check configured credentials: Request failed with status code 401

### ISSUE THREAD

**Issue by hajar97** [ptz0n/homebridge-verisure#149]
Hi there,

I believe I have configured the plugin correctly, but everything HB starts I get this error:
"Unable to get installations. Please check configured credentials: Request failed with status code 401"

When I login through Verisure app it works fine with the same credentials, so its really something with the plugin.

I tried the MFA setup, but instead of getting an MFA tocken, I get a huge dump of JSON. I see my correct login email and password there, but other than that I am not sure what this huge JSON is supposed to mean.

Any idea what may be happening or how to fix it? Thank you.

**Comment by ptz0n** [comment]
Hi and thanks for submitting. Sounds like the MFA is’nt configured correctly.

How many characters is your token? The outputted JSON should be copied into your config file.

https://github.com/ptz0n/homebridge-verisure#multi-factor-authentication

**Comment by hajar97** [comment]
I don't get a token. I get a massive JSON file of multiple hundreds of lines such that it doesn't even fit in scrolling history of output. Even if I find a way to dump this huge JSON file into some file, I am not sure how do I copy it to my config?

**Comment by ptz0n** [comment]
Oh, I see. You should not put that huge output into your config. Do you get any visible errors in the output?

Let me try and see if I can recreate the issue.

**Comment by ptz0n** [comment]
MFA config generator is working fine for me. Which app (and website) are you using and in which region are you located?

**Comment by hajar97** [comment]
I am in Spain. 

The app we have here is My Verisure.

Here is the web interface for it:
https://customers.securitasdirect.es/owa-static/login￼

When I login the first time it asks me to select my phone number from a list of 2 phone numbers that are registered with my account. When I select one it sends an SMS there and asks me to input that SMS code into web form. When I do that it proceeds to login. After that if I login/logout with the same browser I can login with just my email/password, no additional SMS code confirmation is needed.

I believe I need that same SMS login in Homebridge. And somehow that is what is failing and therefore I am unable to login, getting authentication error messages.

**Comment by hajar97** [comment]
The only error I see is at the very end of the very long JSON dump, which says this:
data: {
      errorGroup: 'UNAUTHORIZED',
      errorCode: 'AUT_00001',
      errorMessage: 'Username/password does not match any valid login'
    }

**Comment by hajar97** [comment]
Hi Erik,

Any update on this? am I doing something wrong? Could I try something else out?

Thanks

**Comment by ptz0n** [comment]
I see. You're using a non-Vbox system which is not supported by this plugin. Please have a look at: https://github.com/ptz0n/homebridge-securitas-direct

**Comment by hajar97** [comment]
There seem to be 2, one from you and one from @ottimisgroup. Which one should I use?

￼
