### ISSUE TITLE
Error configuration Multi-factor authentication

### ISSUE THREAD

**Issue by devilman85** [ptz0n/homebridge-verisure#154]
I am having problems with the configuration in question. I run the command in the homebridge terminal but still entering the correct data gives me an error. Solutions?

**Comment by ptz0n** [comment]
Hi & thanks for reaching out.

- What does your configuration look like? **Please redact any email, passwords and cookies.**
- Which command do you run?
- Which version of the plugin do you have installed?
- What error do you get? Please share the logs.

**Comment by devilman85** [comment]
[23/03/2023, 07:34:55] [homebridge-verisure] Unable to get installations. Please check configured credentials: Request failed with status code 401

version 2.0.0 plug in

command : npx homebridge-verisure

             "email": ",
            "password": "",
            "alarmCode": "0000",
            "doorCode": "000000",
            "installations": [
                "Alias"
            ],
            "pollInterval": 60,
            "showAutoLockSwitch": true,
            "showAudioSwitch": true,
            "audioOffValue": "SILENCE",
            "audioOnValue": "HIGH",
            "platform": "verisure",
            "_bridge": {
                "username": "",
                "port": 48651

I didn't understand the cookies question what should I configure

**Comment by fbal21** [comment]
Hello,

I've got a similar problem when using the command "nix homebridge-verisure" on a Synology nas. I've got the following error message:

error: Request failed with status code 401    at createError (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)    at settle (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)    at IncomingMessage.handleStreamEnd (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:293:11)    at IncomingMessage.emit (node:events:539:35)    at endReadableNT (node:internal/streams/readable:1345:12)    at processTicksAndRejections (node:internal/process/task_queues:83:21) {  config: {    transitional: {      silentJSONParsing: true,      forcedJSONParsing: true,      clarifyTimeoutError: false    },    adapter: [Function: httpAdapter],
......
then a full trace of code.

Regards,
