### ISSUE TITLE
Accessories: No response after a while

### ISSUE THREAD

**Issue by Stianker1** [ptz0n/homebridge-verisure#156]
Hello. After the last update, i have noticed that 1-2 times a day all my verisure components get "no respons". I then have to restart homebridge to get them online again. Is this a known problem, or am i the only one? 

Thank you again for this lovely plugin. Makes life a little easier 🙌🏼

---

__Please share your experience with detailed description and logs.__

**Comment by ptz0n** [comment]
Thanks for reaching out. Is this affecting all accessories? I’m experiencing something similar.

Nothing in the logs?

**Comment by d3linma** [comment]
I have the same, just submitted #157

**Comment by ptz0n** [comment]
Closig because of duplicate.

**Comment by ptz0n** [comment]
> Hi and thanks for your efforts for support the new Veriesure APIs so quickly.
> 
> I have used your plugin for a long time without any issues.
> 
> After a few hours of usage the accessories become unresponsive. I have not found a way to reproduce it yet.
> 
> [3/21/2023, 5:58:09 PM] [homebridge-verisure] xxx SmartPlug (Vitrinskåp): Getting current switch state. [3/21/2023, 5:58:17 PM] [homebridge-verisure] xxx SmartPlug (Vitrinskåp): Setting switch state to: true [3/21/2023, 5:58:17 PM] [homebridge-verisure] xxx SmartPlug (Vitrinskåp): Error setting switch state: undefined
> 
> Not sure if it is related but after the upgrade I moved Verisure to a new child bridge?

**Comment by Stianker1** [comment]
Affecting all accessories. No error in log. I get the same log output that user d3linma is.

**Comment by ptz0n** [comment]
I have a feeling that it's related to cookies and/or Verisure switching hosts between `01` & `02. Enabled extensive logging in my environment yesterday and have not yet been able to replicate the issue. Ofc.

Will keep debugging.

**Comment by Sascha81-26** [comment]
I love this plug in and I appreciate the work you all do. I installed the update as soon you released it and and everthing was fine, but today my HomeKit also shows no response for the (verisure) smart lock. All other homebridge plugins are still working.

**Comment by ptz0n** [comment]
> Same issue here. Today even restarting homebridge is not fixing the issue...

That's interesting. So far, a restart have fixed it. Anything in your logs?

**Comment by barthoefs** [comment]
> > Same issue here. Today even restarting homebridge is not fixing the issue...
> 
> That's interesting. So far, a restart have fixed it. Anything in your logs?

Nothing in the logs. 
Re-ran the npx homebridge-verisure. Some values were different, but after restart it still did not work. 
Had to force-quit the home.app. And again all the verisure details moved from all assigned rooms to a "Default room".

btw I had to restart the homebridge instance every day since 2.0

**Comment by ptz0n** [comment]
Thanks for the info. My instance still works, 20 hours and counting without seeing any "No response" error.

**Comment by Sascha81-26** [comment]
(..) all the verisure details moved from all assigned rooms to a "Default room".
> 
— I noticed that, too. I put my smart lock back to my room and then it was in no response.

**Comment by d3linma** [comment]
Mine worked for a long time, but today it stopped responding again

**Comment by ZEEN0j** [comment]
I’m also seeing this. No errors in the logs and a restart of the bridge running Verisure fixes it. Has happened twice since installing 2.0.0

**Comment by priisagersoegaard** [comment]
I have the same problem with my door lock after 2.0.0.
After several hours it stops responding in HomeKit and there is nothing in log.
A restart of Homebridge and it's up and running again for some hours then it stops again.

**Comment by olofbokedal** [comment]
I'm also experiencing this. No errors in the logs, just the good old "Getting current x y z value" every 30 seconds. A restart solves the problem.

Will do some digging of the requests from the native app to see if there's anything going on with the URLs etc.

**Comment by ptz0n** [comment]
Super strange (inconsistent), since I started logging all requests and responses, my instance haven't had any issues for more than five days. Now I've restarted in hope to reproduce the issue.

Cross your fingers 🤞

**Comment by priisagersoegaard** [comment]
> I have the same problem with my door lock after 2.0.0.
> After several hours it stops responding in HomeKit and there is nothing in log.
> A restart of Homebridge and it's up and running again for some hours then it stops again.

A little update - I kept my homebridge running and suddenly my Doorlock was online agian for several hours (without restart of Homebridge) but this morning the status was again "no response" in Home Kit.

**Comment by ZEEN0j** [comment]
About 3 days later and all devices were unresponsive for me again. Very strange

**Comment by crahan** [comment]
I just checked after reading @ZEEN0j's comment and can confirm all devices are unresponsive here as well.

**Comment by ptz0n** [comment]
Same here, finally. I’ll dig into the debug logs tonight 🥳

**Comment by barthoefs** [comment]
> Same here, finally. I’ll dig into the debug logs tonight 🥳

Same here. Do we all have the same issue at the same time...

**Comment by ptz0n** [comment]
Ok, I believe we got it, HTTP 200 with errors:

```bash
{
  message: 'Request Failed',
  locations: [ [Object] ],
  path: [ 'installation', 'armState', 'name' ],
  data: {
    status: 503,
    logTraceId: '…',
    errorGroup: 'SERVICE_UNAVAILABLE',
    errorCode: 'SYS_00004',
    errorMessage: 'XBN Database is not activated'
  }
}
```

**Comment by ZEEN0j** [comment]
Just want to say I appreciate what you are doing. Awesome work and thanks again

**Comment by priisagersoegaard** [comment]
Thanks @ptz0n 
Great work you are doing👍

**Comment by barthoefs** [comment]
Today again all the Verisure devices disappeared again from home.app. 
After restarting I got this messages: 
![Uploading IMG_4888.png…]()

Seems everything is back in home.app

**Comment by Dababa26** [comment]
Une solution ? Même problème également?

**Comment by ptz0n** [comment]
Please update to `v2.0.1` 🎉
