### ISSUE TITLE
Alarm status not activated

### ISSUE THREAD

**Issue by ZEEN0j** [ptz0n/homebridge-verisure#158]
I’m running the latest version 2.0.0

When activating my alarm, either home or away. Everything works as expected except the status icon at the top in the home app. It will still say that the alarm is inactive even when it is in fact active. 

![IMG_0794](https://user-images.githubusercontent.com/36206520/228080290-a8e715e6-4baf-4cc7-b297-7da61a0283fa.jpeg)

**Comment by ptz0n** [comment]
I'm pretty sure the icons in category bubbles/buttons on the top is static. E.g. they never change.

**Comment by ZEEN0j** [comment]
I mean the top one that says Säkerhet - Avaktiverat. The bottom line of that button is dynamic. The lights one shows how many light are on etc. Maybe I’m imagining this but I’m pretty sure it said activated before the 2.0.0 update.

**Comment by ptz0n** [comment]
Closing until we figure out what's the expected behaviour.
