### ISSUE TITLE
Yale Doorman "Status"

### ISSUE THREAD

**Issue by FamJohansson** [ptz0n/homebridge-verisure#16]
Yale Doorman Lock/Unlock Is running perfect.

My door are closing automatically after few seconds. And then the door is displayed as open in Apple Home app.

Can you add check for door status?

I think you can use my earlier information when you added Yale Doorman Lock/Unlock.

**Comment by ptz0n** [comment]
It might be a good idea to add polling functionality for all door and window statuses. Let's say every 30s.
