### ISSUE TITLE
Impossible to get cookie infos

### ISSUE THREAD

**Issue by ThibaultTourailles** [ptz0n/homebridge-verisure#166]
I'm trying to setup this plugin on Homebridge for the first time. 
To get the cookies info to setup I'm following the README and run `npx homebridge-verisure`
But two things:
- First you seem to require an email and up until now, I'm using a username in the app to login
- Trying with either the username or email, I get a 401 ```data: {
      errorGroup: 'UNAUTHORIZED',
      errorCode: 'AUT_00001',
      errorMessage: 'Username/password does not match any valid login'
    }```

I tried setting up my alarm with Jeedom and their plugin, and they request an installation category (1 or 2), and it seems related to the country (and I managed to login, but could not connect Verisure through Jeedom on Homebridge). Is it taken into account? (I'm located in France)

I tried to find more information on the internet but there's no public API just brave people like you trying to reverse it (so kudos for that). 
If you need any more information don't hesitate to ask.

**Comment by ptz0n** [comment]
This plugin only support Vbox installations. Which app do you use?

**Comment by ptz0n** [comment]
Unfortunately, that's a different API. I've started a different project over here but ran into issues because the API was so slow: https://github.com/ptz0n/homebridge-securitas-direct
