### ISSUE TITLE
Lock status not updating if using lock without HomeKit.

### ISSUE THREAD

**Issue by tuomaslaa** [ptz0n/homebridge-verisure#22]
Goal: To use both HomeKit and Verisure App/Tags/Keypad with Yale Doorman and still have always lock/unlock status updates on Homekit.

Solution: Add simple polling with customized interval

**Comment by tuomaslaa** [comment]
Below is the solution.  Line 336. 

`  setInterval(function() { service.getCharacteristic(Characteristic.LockCurrentState).getValue() }, 45000);`

**Comment by ptz0n** [comment]
Good catch, some kind of ping/poll is important for most accessories.

Please open a PR with the proposed changes.

**Comment by ZEEN0j** [comment]
Where do I edit this if I want to fix it?

**Comment by ZEEN0j** [comment]
@ptz0n thanks. But where do I place the js file? In Verisure nock modules? Or do I configure the Homebridge config?

**Comment by ptz0n** [comment]
It would be nice to have this as part of the `VerisureAccessory` constructor and enable in the subclasses where applicable?

**Comment by ZEEN0j** [comment]
I think you misunderstood me. That went over my head. How do I add this so I can fix my setup so I don’t get errors when unlocking my door? I copy paste code. I can’t edit it :)

**Comment by ptz0n** [comment]
@ZEEN0j Oh, I'm really sorry about that. Let me have a look this weekend.

**Comment by ptz0n** [comment]
Did some tests and this approach works great. Hopefully pushing a new version this weekend 👍🏼

**Comment by tuomaslaa** [comment]
Thank you. It works.
