### ISSUE TITLE
Yale Doorman/Smartlock does not appear in 1.7.0-rc.0

### ISSUE THREAD

**Issue by bliatun** [ptz0n/homebridge-verisure#28]
Have a Smartplug and a Smartlock working in 1.6.0.

Only the Smartplug is showing in 1.7.0
-no sign of the Smartlock, and no error in the homebridge log.

Both working when reverting back to 1.6.0 again.

**Comment by ptz0n** [comment]
Thanks for reporting! Can you please share the logs from initializing/starting homebridge w. plugin version `1.7.0-rc.0`?

**Comment by bliatun** [comment]
Sendt you an email with logs.

**Comment by ptz0n** [comment]
Great find! I did a brain fart in the conditional for when to initialize the door lock accessory. Fixed by  https://github.com/ptz0n/homebridge-verisure/pull/27/commits/51da699f737c8ef8037cd1028d45f47caf7db38c, published in `1.7.0-rc.0`.

Please update & try again 👍

**Comment by bliatun** [comment]
Thanks! It works perfectly now!
