### ISSUE TITLE
No polling for magnetic sensor values

### ISSUE THREAD

**Issue by ZEEN0j** [ptz0n/homebridge-verisure#32]
Everything is showing up and working except the magnetic sensors. If I open a door it's not reflected in the home app. Poll interval is set to 60

**Comment by ZEEN0j** [comment]
To make it update I have to open and close the app. Anything negative with setting the interval to 1 sec? Also what is the difference when setting the alarm, I have four options. Home, away night and off. Home and night seems to do the same thing (skalskydd) and away turns the alarm ON. Or am I missing something. 

Just want to say thanks as well for the awesome work

**Comment by ptz0n** [comment]
Thanks for posting this issue! Currently, we only poll alarm and door locks for updated values. I don't see any problem with adding polling for contact sensors too.

I would not recommend setting the interval that low, as Verisure might rate limit requests. Would polling every minute be often enough in your setup?

**Comment by ZEEN0j** [comment]
Ok then, I’ll set it higher. Reason why the lower value is I want instant notifications or automations when a door or lock opens. 

What’s the correct phrase to set the alarm using Siri? It either doesn’t understand or it sets a alarm on the phone.

**Comment by ptz0n** [comment]
Sadly, we do not have access to any subscription based notification from Verisure. Therefore we need to poll for state changes. I guess that every 30 seconds or so would be instant enough in your case?

Please try out #33
