### ISSUE TITLE
Username/password does not match any valid login

### ISSUE THREAD

**Issue by ben4523** [ptz0n/homebridge-verisure#39]
hi when i configure your module i have this error message : 
`Error: <response><status><errorGroup>UNAUTHORIZED</errorGroup><errorCode>AUT_00001</errorCode><errorMessage>Username/password does not match any valid login</errorMessage></status></response>
    at verisure.getToken.then (/usr/local/lib/node_modules/homebridge-verisure/lib/platform.js:81:72)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
but my email and password work in myverisure app. For myverisure app i use username and not email for connect. This plugin it's for verisure https://www.verisure.fr/ ? thanks

**Comment by ptz0n** [comment]
Is this the one? https://itunes.apple.com/fr/app/my-verisure/id385076046

**Comment by ben4523** [comment]
Yes excact !

**Comment by ptz0n** [comment]
That app seem to be using a different set of API’s and therefore is not compatible, sorry.

If you have a VBox system, you should be able to use the following app along with this plugin.

https://itunes.apple.com/se/app/verisure/id423747572

**Comment by ben4523** [comment]
you can give me the information api about this app ? i put in the plugin !

**Comment by ptz0n** [comment]
The API’s are not public. You need to use something like Wireshark or Charles Proxy to view the HTTPS requests being sent from the app.

**Comment by ptz0n** [comment]
Closing as the client mentioned seem to be using a totally different API. I'm happy to review a PR enable use of this API.

**Comment by ptz0n** [comment]
@ben4523 Some progress is finally being made. Please head over here to help out: https://github.com/ptz0n/node-verisure/pull/41
