### ISSUE TITLE
SubZero temperatures

### ISSUE THREAD

**Issue by mikalmo1** [ptz0n/homebridge-verisure#43]
I have the Verisure climate sensor mounted outdoors. It is now winter in Norway and the temperatures are pretty much below zero degrees Celsius all the time. However, the climate sensor reports 0,0° to the home app. My understanding is that this is caused by some minValue set to 0 somewhere, but I have no idea how to fix/edit this. Can something be done to the plugin?

**Comment by ptz0n** [comment]
Thanks for reporting, I'll have a look.

**Comment by ptz0n** [comment]
Should be fixed in `v1.9.2`, please try it out.
