### ISSUE TITLE
Possibility to change auto lock status on/off with a switch

### ISSUE THREAD

**Issue by tuomaslaa** [ptz0n/homebridge-verisure#44]
It would be nice feature to to disable / enable auto locking of the Yale doorman smart lock via HomeKit switch. This is doable via Verisure API.

**Comment by ptz0n** [comment]
I see, how would you like this feature to be controlled? Would it make sense to set it up as a switch, like a SmartPlug?

Can you provide any request/response data to toggle this feature? __Please sanitize any credentials.__

**Comment by tuomaslaa** [comment]
Yes like a switch would be great. You can see example code in here (Python). It's get_lock_config and set_lock_config methods: https://github.com/persandstrom/python-verisure/blob/master/verisure/session.py 

and the api url is mentioned in here: https://github.com/persandstrom/python-verisure/blob/master/verisure/urls.py

it's:  installation(guid) + 'device/' + device_label + '/doorlockconfig'

**Comment by ptz0n** [comment]
Sounds like a plan but I don't have a door lock so any help with testing a pre-release would be much appreciated.

**Comment by skegget** [comment]
I can assist with some testing, just let me know what I need to do.

**Comment by tuomaslaa** [comment]
I can also test before the release

**Comment by tuomaslaa** [comment]
Any news on this?

**Comment by ptz0n** [comment]
Thanks for the ping. I have some draft code locally. Wanna spend some time with this tonight 👍

**Comment by ptz0n** [comment]
I just pushed a rough draft. Please try it out 🚪

__Update the plugin globally__

```bash
$ npm install -g git://github.com/ptz0n/homebridge-verisure#dev
```

__Alt. run it manually__

```bash
$ git clone https://github.com/ptz0n/homebridge-verisure.git
$ cd homebridge-verisure
$ git checkout dev
$ npm install
$ homebridge -P .
```

**Comment by hansherlighed** [comment]
I've tested the function and it seems to work. I can enable and disable the AutoLock function of the lock.

Thx.

**Comment by ptz0n** [comment]
Thanks for trying it out @hansherlighed. Currently, the switch service is named the same as the door lock it's configuring.

Do you think we should append the service name with "auto lock"? How is this config named in the Verisure mobile application and/or web interface? Please share screenshots, if you feel comfortable.

Suggestion:
> SmartLock (Kitchen) Auto lock

**Comment by hansherlighed** [comment]
I think it would be good to name it something like you suggest.
In the Verisure App, the auto lock feature is just a checkbox with the text "Automatic Locking"(the text string is localized to your Iphone language).
I would keep the name as short as possible since the name gets cut on the "home" screen where your favorites are shown.
The default naming pattern in the Home app on Iphone is:
Room Name
Device name
Status

So in my case on the "Home" page I only see:
Entrance
Smartlock...
On

So perhaps the best name you could give it would be something like "AutoLock (Kitchen)"

**Comment by ptz0n** [comment]
Thanks again for your in depth suggestion. I really like "Auto-lock (Kitchen)".

**Comment by ptz0n** [comment]
The new naming of the switch service is now available on the `dev` branch. Please update & try it out.

**Comment by tuomaslaa** [comment]
I got this error: 

``
[2019-2-1 18:52:08] [Verisure] Initializing platform accessory 'undefined'...
Feb  1 18:52:08 homebridge homebridge[31089]: [2019-2-1 18:52:08] [Verisure] Error: Accessories must be created with a non-empty displayName.
Feb  1 18:52:08 homebridge homebridge[31089]:     at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:47:27)
Feb  1 18:52:08 homebridge homebridge[31089]:     at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:426:21)
Feb  1 18:52:08 homebridge homebridge[31089]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:394:32)
Feb  1 18:52:08 homebridge homebridge[31089]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Feb  1 18:52:08 homebridge homebridge[31089]:     at verisure.getToken.then.then.then (/usr/lib/node_modules/homebridge-verisure/lib/platform.js:90:9)
Feb  1 18:52:08 homebridge homebridge[31089]:     at <anonymous>
Feb  1 18:52:08 homebridge homebridge[31089]:     at process._tickCallback (internal/process/next_tick.js:189:7)
Feb  1 18:52:08 homebridge homebridge[31089]: (node:31089) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
Feb  1 18:52:08 homebridge homebridge[31089]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
Feb  1 18:52:08 homebridge homebridge[31089]:     at verisure.getToken.then.then.then.catch (/usr/lib/node_modules/homebridge-verisure/lib/platform.js:94:9)
Feb  1 18:52:08 homebridge homebridge[31089]:     at <anonymous>
Feb  1 18:52:08 homebridge homebridge[31089]:     at process._tickCallback (internal/process/next_tick.js:189:7)
Feb  1 18:52:08 homebridge homebridge[31089]: (node:31089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Feb  1 18:52:08 homebridge homebridge[31089]: (node:31089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``

**Comment by ptz0n** [comment]
Ough, sorry about that one! Should be fixed now. Please update 🔌

**Comment by ptz0n** [comment]
Let's continue discussion in #49.
