### ISSUE TITLE
Smoke detectors as triggers

### ISSUE THREAD

**Issue by mikalmo1** [ptz0n/homebridge-verisure#45]
Is it possible to make the smoke detectors act as triggers for automation? For the time being I can only use the magnetic door sensors do that. It would  be smooth being able to for example have all the lights  go to 100% if a smoke detector goes off. Or if you could have a smart plug enabled heating device turned on if the temperature goes below a set value.

**Comment by ptz0n** [comment]
Temperature devices is not supported as triggers in the Apple Home app, but they are supported by the HomeKit protocol.

I would recommend using the [Eve for HomeKit](https://itunes.apple.com/se/app/eve-for-homekit/id917695792) to setup these automations. In the Eve app, they are called Rules.

When you have them configured using the Eve app, they will show up as automations in the Home app too. If you need to edit them, just head back to the Eve app.
