### ISSUE TITLE
Alarm changes state by itself

### ISSUE THREAD

**Issue by ZEEN0j** [ptz0n/homebridge-verisure#50]
With latest release I'm getting a weird issue. When setting the alarm to night mode, it switches correctly and the Verisure app shows the same thing. 10 seconds later it switches to home mode in the home app and my devices get notifications of the change. When checking the verisure app it still says that it's on night mode correct behavior. Somehow the home app gets confused of the actual state

**Comment by ptz0n** [comment]
Verisure does not actually have an arm state that represents "Night". Currently this arm state is mapped to the same as "Home". This is the root cause of the unintuitive flow you describe above.

Therefore I think it would be more intuitive to remove support for this arm state altogether.

**Comment by ZEEN0j** [comment]
If it does nothing imo I would remove it. I had my automations set to home but I had to reinstall Homebridge for another issue and when doing the setup I forgot and set them all to night. All is working again with them set to home. 

Removing it would make it more clear for new users

**Comment by ptz0n** [comment]
Setting arm state should look like this:

<img width="901" alt="screenshot 2019-02-04 at 07 43 00" src="https://user-images.githubusercontent.com/200250/52200284-a9ae6800-2868-11e9-8408-aaf353508bb0.png">

**Comment by ZEEN0j** [comment]
That looks great
