### ISSUE TITLE
Disable arm/disarm of alarm

### ISSUE THREAD

**Issue by olofbokedal** [ptz0n/homebridge-verisure#52]
I don't know if it's even possible due to limitations in HomeKit, but I'd prefer to arm and disarm the alarm via Verisures solutions only. In other words, I'd like to see the alarm status and create scenarios based on the status, but not be able to change it. Having a device laying around at home, i.e. an iPad, with Siri enabled would create a potential security breach by simply saying "Hey Siri, disarm the alarm".

Maybe the alarm needs to be exposed as a different accessory, or maybe even multiple accessories like a switch which indicates the status and a motion sensor which triggers if someone sets of the alarm.

I'll probably fork the repo and start playing around in order to see what's even possible. But please enlighten me if this is impossible for some reason :)

**Comment by ZEEN0j** [comment]
About the security risk. Don't you need to authorize before being able to open doors or disabling alarms. At least I need to. So screaming hey Siri into a house shouldn't work

**Comment by olofbokedal** [comment]
I haven't tried with Siri yet, but I was able to turn it off via the Home app on my iPhone without any authorization. The phone was unlocked though, so maybe that's enough authorization according to HomeKit? Never had an alarm connected via HomeKit before so I don't know much yet.

**Comment by ZEEN0j** [comment]
Yes. If phone is unlocked it will work. Try control center on the lock screen without having previously unlocked the device. It won’t work

**Comment by olofbokedal** [comment]
If so I think this issue is not an issue, at least for me, anymore. I'm gonna try different scenarios and see if there might be a security breach someway.

Having a hard time finding any documentation from Apple regarding this. Surely there must be some place where they've written how an alarm is handle via HomeKit?

**Comment by ptz0n** [comment]
I'm always prompted to unlock the device in order to change the security system state.

Maybe we should clarify in the readme; that any device that have permission to alter the security system alarm or door lock states should be locked when not actively in use.

**Comment by olofbokedal** [comment]
That's a good idea. At least me, who never worked with a security system via HomeKit before, would feel more secure knowing how HomeKit handles this natively. The last thing anyone would want to do is to implement a third party solution which would compromise the security, and just knowing about how this is handled would make it feel more secure.

**Comment by ptz0n** [comment]
From [Apples HomeKit Accessory FAQs](https://developer.apple.com/support/homekit-accessory-protocol/):

> __What security features does HAP use?__
> All sessions between HomeKit accessories and Apple products over HAP are end-to-end encrypted and mutually authenticated.

**Comment by olofbokedal** [comment]
🥇 

I've just tested both automatic scenarios and Siri, and I was required to unlock my phone every time. 

- Activate the alarm when leaving home = push notification asking me to confirm
- Disabling when I got home = push notification asking me to confirm
- Asking Siri to disable when not at home = Siri told me to authenticate using TouchID

So all seems good. My initial idea is simply not necessary anymore.

**Comment by ZEEN0j** [comment]
What’s really nice about the new toggle for automatic door lock is that you can set an automation that turns it on when leaving for example. This will then lock the door in the case that you forgot it. Then with a timer it will disable it again after x amount of minutes (I have my reasons why I don’t leave it on). But doing it this way you don’t need to authenticate when leaving as it isn’t  HomeKit that locks the door but Verisure.
