### ISSUE TITLE
AutoLockState

### ISSUE THREAD

**Issue by torandreroland** [ptz0n/homebridge-verisure#57]
The AutoLockState service is always unreachable while the lock itself is reachable.

**Comment by ptz0n** [comment]
Thanks for reaching out. Can you please share some logs so we can determine what's going wrong?

**Comment by torandreroland** [comment]
The only thing being logged with regards to the AutoLockState is "[Verisure] info SmartLock (Front Door): Getting current auto lock config.". This is when I when long press the service in the Apple Home-app. Nothing is being logged when I start the Homebridge server, not even in debug mode.

**Comment by ptz0n** [comment]
Is the auto lock config available in the Verisure app?

**Comment by torandreroland** [comment]
Yes, I believe so. See screenshot here: https://www.dropbox.com/s/izloa7pmnn1feia/IMG_0275.JPG?dl=0 . Norwegian language, so look for “automatisk låsing”. Also note that it has been like this since support for this service was added back in February.

**Comment by skegget** [comment]
Do you have a separate Verisure user for the HomeKit integration? I believe you need to set the correct Verisure user rights on your Verisure account page (I think it has to be administrator). I had this issue myself some time ago.

**Comment by torandreroland** [comment]
Yes, I have! Changed the user to administrator and that solved it. Thank you very much, @skegget!

Maybe add this information to the readme, @ptz0n? Or perhaps a config to disable the auto lock-service for those who don’t want to elevate the user’s rights?

**Comment by ptz0n** [comment]
Oh, I see. This should have yielded an error in the logs, I'll look into that.

We should definitely add some info about access rights to the readme, good thinking!
