### ISSUE TITLE
Armed / disarmed and door / window status?

### ISSUE THREAD

**Issue by MichaelMMX** [ptz0n/homebridge-verisure#7]
Hi,

Do you have plans to include door / window status and alarm status (armed / disarmed)?

```
  "armState": {
    "statusType": "DISARMED",
    "date": "2017-01-01T00:00:00.000Z",
    "name": "Johnny Walker",
    "changedVia": "TAG"
  },
  
      "doorWindowDevice": [
      {
        "deviceLabel": "HJKL 6789",
        "area": "entrance door",
        "state": "CLOSE",
        "wired": true,
        "testDate": "2017-01-01T00:00:00.000Z"
      }
    ]  
```

**Comment by ptz0n** [comment]
Great suggestions 👍 but feel free to submit a PR.

**Comment by Merlinuf** [comment]
This would be nice to have the door sensors added, is it coming?

**Comment by RienduPre** [comment]
Any new on this ?

**Comment by ptz0n** [comment]
Implementation for contact (door/window) sensors is now available in the `dev` branch which will hopefully be merged soon. 🎉
