### ISSUE TITLE
Disable Auto-lock switch with iOS 13 accessory bundling

### ISSUE THREAD

**Issue by diamolly** [ptz0n/homebridge-verisure#73]
Hi. Is it possible to remove the auto-lock switch via the config file? After iOS 13 some accessories are bundled together under one tile in HomeKit. The Yale Doorman in Verisure  does this it appears. The lock itself and the auto-lock switch bundles together under the lock tile and now shows the state of the auto-lock (on/off and not the lock status (open/locked) on the lock tile. And since the auto-lock is just a power plug switch it is shown as powered on/off.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/20912827/65638803-2f914600-dfe7-11e9-8989-9d141d00fee2.png">

I would love if there was a way to remove or disable the auto-lock switch from Homekit so only the open/locked state showed on the lock tile. 

Thank you for your hard work on this plugin, I really love it and appreciate it :)

**Comment by skegget** [comment]
FYI - This is solved in iOS 13.2 beta where you can choose to group/ungroup related tiles.
