### ISSUE TITLE
TypeError: Cannot read property 'giid' of undefined

### ISSUE THREAD

**Issue by jacobwod** [ptz0n/homebridge-verisure#8]
Hi,

It seems like the underlaying verisure plugin can't get any installations from the API:

    /usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:50

    giid = typeof installation == 'string' ? installation : installation.giid
                                                                        ^

    TypeError: Cannot read property 'giid' of undefined
        at Object.overview (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:50:73)
        at /usr/local/lib/node_modules/homebridge-verisure/index.js:90:16
        at /usr/local/lib/node_modules/homebridge-verisure/index.js:37:7
        at Request._callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:45:7)
        at Request.self.callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/request/request.js:188:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/request/request.js:1171:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)

It's been working great for a day or so, but now homebridge won't start because of this. Could it be that Verisure is throwing us away for some reason?

**Comment by jacobwod** [comment]
It looks as the endpoint is down, as I can't get the token in response from `auth()`. Here's the output from the `auth()` method of verisure module (from /usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure), that is supposed to be the token:
`<response><status><errorGroup>SERVICE_UNAVAILABLE</errorGroup><errorCode>SYS_00004</errorCode><errorMessage>XBN Database is not activated</errorMessage></status></response>`

No wonder further requests fail. Anyone else having this issue?

**Comment by jacobwod** [comment]
Solved (kind of).
Change API_HOST from 'e-api02.verisure.com' to 'e-api01.verisure.com' in /usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js.
I'm not sure how to merge this change with your repository, but it's an easy fix at least. 

An even better solution would be to automatically switch between 01 and 02 endpoints, but I'm not sure how to do that.

**Comment by ptz0n** [comment]
@jacobwod It's not quite that easy, as Verisure seem to use both hosts depending on their daily mood. We need some retry logic for both hosts.
