### ISSUE TITLE
Missing support for Verisure Spain (Securitas Direct)

### ISSUE THREAD

**Issue by artik** [ptz0n/homebridge-verisure#80]
I was wondering if this config could also work for verisure spain (Securitas direct). As the login is a number, and not an email it doesn't work.

If somebody knows a workaround or a solution, it will be really appreciated

**Comment by ptz0n** [comment]
Hi & thanks for reaching out.

Currently, this plugin only supports the Vbox systems. I see that others have added support for Securitas Direct to Home Assistant:

https://github.com/segalion/securitasdirect

It’s not the first time this question is asked. Do you think that the plugin should support both API’s?

**Comment by artik** [comment]
Thanks for your answer. Yes it would be a great step, as both companies are the same. As the home assistant developer said, if it works for Securitas spain, it should also works for more countries (France, etc).

As I'm equipped with Securitas, feel free to contact me for any help or test if you bring this plugin live. And maybe a sponsor could help you ?

**Comment by ptz0n** [comment]
It would be great if we could setup accessories to support the different Verisure API's. Let's start by adding support to [node-verisure](https://github.com/ptz0n/node-verisure).

Ref: [Cebeerre/VerisureAPIClient](https://github.com/Cebeerre/VerisureAPIClient)

**Comment by artik** [comment]
Ok, anything I have to do in this process?

**Comment by Cebeerre** [comment]
Hi @ptz0n , @artik made me aware of this, so I just uploaded my documentation around the Verisure EU mobile endpoint. It probably helps better than reading my python code.

**Comment by ptz0n** [comment]
@Cebeerre Wow, good job! I’ll take a closer look.

**Comment by artik** [comment]
@Cebeerre thanks for sharing, it can help so many Homekit+verisure EU users.

**Comment by Xivi08** [comment]
Hi!

I'm interested into know if there is any update on this.

Ty!

**Comment by artik** [comment]
Hi @ptz0n, any update about the implementation of Securitas?

**Comment by ptz0n** [comment]
I’ve started to mock the responses and looked into tooling to enable collaboration because I dont personally have access to a Securitas installation.

The last part is actually quite troublesome. Please share your ideas 👍🏼

**Comment by ptz0n** [comment]
I might have got something working, please head over to: https://github.com/ptz0n/node-verisure/pull/41

**Comment by jeremybdk** [comment]
Hello @ptz0n,
What are the next steps here to integrate this into your home bridge module? I tested your plugin here https://github.com/ptz0n/node-securitas-direct and it's working correctly for my French Installation. Do you plan to add these features to homebridge ?
Thanks

**Comment by ptz0n** [comment]
@jeremybdk Thanks for your comment. I'm currently working on a separate plugin for Securitas Direct which will use the client you mentioned.

No hard release date set, but I hope to get it out within a few weeks.

**Comment by GerSant** [comment]
> @jeremybdk Thanks for your comment. I'm currently working on a separate plugin for Securitas Direct which will use the client you mentioned.
> 
> No hard release date set, but I hope to get it out within a few weeks.

Any news @ptz0n ? :) Thanks!!!

**Comment by ptz0n** [comment]
Beta plugin published, please help out with testing: https://github.com/ptz0n/homebridge-securitas-direct
