### ISSUE TITLE
Smoke detector as an actual smoke detector

### ISSUE THREAD

**Issue by skegget** [ptz0n/homebridge-verisure#83]
Currently the Verisure smoke detector shows up as a temperature and humidity sensor in HomeKit. Would it be possible to define it as an actual HomeKit smoke detector as well?

**Comment by ptz0n** [comment]
We don’t currently get the state from Verisure more frequently than every 30 seconds or whatever you have configured.

This means that there will be a delay to report detected smoke via the HomeKit protocol.

In the case of smoke being detected, I personally trust Verisure to notify me via SMS and/or push notification faster than we could notify users via HomeKit.
