### ISSUE TITLE
Cant connect Homebridge to HomeKit while having Verisure plugin installed

### ISSUE THREAD

**Issue by Holseker** [ptz0n/homebridge-verisure#86]
Hi,

This has been working before, but today the Verisure components fell out. I had Homebridge on Mac OS x and tried set up a new Homebridge on Rasp Pi 4. I Deleted my home, but could not add Homebridge as accessorie. I tried on my Mac and not there either. Have updated everything. 

The alarm components will show in Homebridge on the computer and they are working fine from there. As soon i remove the Verisure plugin i can add the Homebridge to HomeKit again working fine.

This is on both the Mac and the Pi. The only difference from before is that when i try to add Homekit to HomeKit i get the message "Could not add Homebridge"

**Comment by Holseker** [comment]
{
    "bridge": {
        "name": "Homebridge A470",
        "username": "0E:74:14:48:59:38",
        "port": 51430,
        "pin": "816-38-175"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "forceCt": true,
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"
        },
        {
            "platform": "verisure",
            "name": "Verisure",
            "email": "email",
            "password": "password",
            "alarmCode": "code",
            "doorCode": "code",
            "pollInterval": 60
        }
    ]
}

**Comment by bartgabriels** [comment]
Same issue appears here. I changed already the poll interval, but no luck ...
```
            "platform": "verisure",
            "name": "Verisure",
            "email": "***@****.be",
            "password": "********",
            "alarmCode": "0000",
            "doorCode": "000000",
```
            
Other loaded plugins:
- WeatherPlus
- Ewelink Max

**Comment by Holseker** [comment]
I tried the homebridge-verisure-ts plugin now just to see if that works and it does. But ofcourse outdated and unusable

**Comment by hoefs** [comment]
Here it is still working with homebridge 1.0.3:

```
        {
            "platform": "verisure",
            "name": "Verisure",
            "email": "xxx@xxx.com",
            "password": "xxxxxxx",
            "alarmCode": "xxxx"
        },
```

**Comment by Holseker** [comment]
I Just updated to 1.0.3 and now it works here again too

**Comment by ptz0n** [comment]
Ok, so you used an outdated version pf Homebridge? Can you please share some logs from when it didn’t work?

**Comment by bartgabriels** [comment]
No specific logs where shown, but it didn't work in Version 1.0, 1.1 and 1.2. Homekit became responding again after removing the Verisure plugin.

Check also the releasenotes of the new 1.0.3 version: https://github.com/homebridge/homebridge/releases

> Some users were seemingly unable to pair new homebridge instances or encountered "no response" for all of their accessories if plugins chose to supply an empty serial number for their accessory information. This is now resolved.

**Comment by Holseker** [comment]
Hi.

I used 1.0.1 and it suddebly stopped working. Tried setting up Homebridge and Homekit again but no luck. Then i updated to 1.0.2 and still nothing. Worked when i removed Verisure plugin. 

Today the 1.0.3 came out and this fixed the problem.

Where can i find the logs?

**Comment by ptz0n** [comment]
Great, than we don't have an issue with the plugin.

Logs can be found wherever you store them. By default it's being outputted by Homebridge to stdout.

Are you using any process manager like PM2 or nodemon?
