### ISSUE TITLE
Is this plugin stil operational?

### ISSUE THREAD

**Issue by PrimaryInc** [ptz0n/homebridge-verisure#89]
Hi, 

Just wondering if plugin stil is operational.
Installed on homebridge version 1.1.2, latest plugin from web ui.
But no config is added adter install, and no settings page available. 

Thanks :)

**Comment by ptz0n** [comment]
Hi, the plugin is operational. I’m not familiar with the web UI you are referring to.

**Comment by PrimaryInc** [comment]
Hi @ptz0n, 

First thanks for creating plugin. Probabply could done this conversation in Norwegian, your Norwegian right?
WEB UI, it is an extention to HomeBridge for esier management:
![WEB UI 01](https://user-images.githubusercontent.com/45151934/91423482-e41b9380-e858-11ea-9ed8-1ce144728540.PNG)

Im not that goo at json so it is very helpful putting code in at its correct place.
Tried to manually add code but get json config error, hens my bad skills.. :)

**Comment by PrimaryInc** [comment]
No comment?

**Comment by marcjordant** [comment]
Hi @PrimaryInc 

This is still working. You have to add an item in the _**platforms**_ part:

        {
            "bridge": {
                "name": "HomebridgeXXX",
                "username": "********",
                "port": ****,
                "pin": "****"
            },
            "accessories": [
            ],
            "platforms": [
                {
                    "name": "Config",
                    "port": ****,
                    "platform": "config"
                },                              <========
                {                               <========
                    "platform": "verisure",     <========
                    "name": "Verisure",         <========
                    "email": "******",          <========
                    "password": "*****",        <========
                    "alarmCode": "****"         <========
                }                               <========
            ]
        }

Be sure to replace the _****_ with your values.

**Comment by PrimaryInc** [comment]
@marcjordant.,

Thanks I'll have a go :)

**Comment by ptz0n** [comment]
The UI was new to me and I don’t know how the config properties are pulled into the views in order to generate a working config for each plugin.

Please share if you have any pointers.

**Comment by PrimaryInc** [comment]
Hi @ptz0n,

Sorry I dont have any ideas. But I've been chating with @afharo about this plugin:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum
Perhaps he can be of asssitance :)

**Comment by afharo** [comment]
@ptz0n FYI, if you want your plugin to show a config UI editor in the plugin `homebridge-config-ui-x`, you can add a file `config.schema.json` to the root of your plugin.

The specifications of that JSON schema are detailed in https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI

It's def not a mandatory thing to have in your plugin, but it helps many users that use that UI homebridge plugin to maintain their installation and don't want to mess up with JSON editing 😉 

PS: I'm not the maintainer of that plugin either, I guess @PrimaryInc mentioned me because I have it in the plugin I maintain 🙂

**Comment by PrimaryInc** [comment]
@afharo,
Thanks for replying, and yes you are correct. Becase your plugin uses web ui :)
And you are spont on about messing up json ;)

Hope this helps @ptz0n :)

**Comment by ptz0n** [comment]
Thanks for your efforts. Plugin version `1.12` have been published which includes the schema. Happy configuring 🎉

**Comment by PrimaryInc** [comment]
@ptz0n  thank you :) I'll have a go in a moment, thanks again :)

**Comment by marcjordant** [comment]
@ptz0n seems there is a small bug with the new version:

`Error: The requested platform 'Verisure' was not registered by any plugin`

Using the new plugin Settings screen, it sets the platform name to 'Verisure' (so with a capital V). 
This produce the error.

    {
            "email": "***",
            "password": "***",
            "alarmCode": "***",
            "pollInterval": 60,
            "platform": "Verisure"
    }

If I manually change it to lower case 'v' (so 'verisure'), it works then.

    {
            "email": "***",
            "password": "***",
            "alarmCode": "***",
            "pollInterval": 60,
            "platform": "verisure"
    }

**Comment by PrimaryInc** [comment]
@marcjordant ,

Do your buttons in home app work as well?
Lock and unlock does not work for me. I get a no response feedback from home app see #90

**Comment by marcjordant** [comment]
@PrimaryInc I don't have any door lock so I cannot say

**Comment by ptz0n** [comment]
Schema typo corrected in `v1.12.1`.

**Comment by PrimaryInc** [comment]
@marcjordant no problem, I did solve the issue. I misstyped mye code with 7 digits instead of 6. Problem solved :)
