### ISSUE TITLE
Error giid

### ISSUE THREAD

**Issue by Bjornies** [ptz0n/homebridge-verisure#9]
Hi, trying to start but get this error message:
[2017-3-24 14:57:14] Loading 0 accessories...
Load homebridge-verisure.verisure
/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:50
    giid = typeof installation == 'string' ? installation : installation.giid

TypeError: Cannot read property 'giid' of undefined

//Björn

**Comment by ptz0n** [comment]
Thanks for posting. Verisure is changing the `API_HOST`. I will try to figure that out.

**Comment by ptz0n** [comment]
This should now be fixed, closing.
