### ISSUE TITLE
json error - home app error

### ISSUE THREAD

**Issue by PrimaryInc** [ptz0n/homebridge-verisure#90]
Hi @ptz0n,

I tested adding code via UI this morning.
Code added:
        {
            "email": "email",
            "password": "Password",
            "doorCode": "xxxxxxx",
            "pollInterval": 60,
            "platform": "Verisure"
        }
This look correct to me, but homebridge gives me an error:
![Verisure01](https://user-images.githubusercontent.com/45151934/91937663-b1f3b100-ecf2-11ea-8c7c-e173351a1f40.PNG)
And then wont start.

Seems that the error is because of the error:
"The requested platform 'Verisure' was not registered by any plugin.
Plugin seems to have loaded as it should:
![Verisure02](https://user-images.githubusercontent.com/45151934/91938118-ad7bc800-ecf3-11ea-8fb7-4cc2ec5d9b04.PNG)

**Comment by PrimaryInc** [comment]
Ah, I see it now.
Loaded plugin is names versiure and the config platform is Verisure. 
Registered platform must either have the name Verisure vith a capital V or config written to json must have al lower cases.

Probably a quick fix for you @ptz0n 👍 
I've simply changed my config in json to:
"platform":"versure"
And config works, but seems that the "look" function is not working.

**Comment by ptz0n** [comment]
Oh, yes. Schema file has now been corrected.

Regarding the lock state this seem to be related to the Home app timing out. Are you currently at home or controlling the lock remotely?

**Comment by PrimaryInc** [comment]
@ptz0n, 

So I did see it now, wrong "code" for my door. Or more presise a type typing 7 digits not 6. My bad.

I also updated the plugin, I only have a door lock and it now works great, thanks :)
