### ISSUE TITLE
Appstore white coloured verisure app credentials not recognised

### ISSUE THREAD

**Issue by Jai-Gogineni** [ptz0n/homebridge-verisure#91]
Hi my credentials with mobile number & password not an email & password, with mobile number & password not recognised in UK.

![image](https://user-images.githubusercontent.com/6741795/93102016-e9733d80-f6a2-11ea-850a-752d2320375e.png)

Thanks
Jai

**Comment by ptz0n** [comment]
We are working to support Verisure UK, please see: https://github.com/ptz0n/homebridge-verisure/issues/80

**Comment by Jai-Gogineni** [comment]
Thanks @ptz0n for the update I am happy tp contribute anything that you may need such as API requests & response etc, let me know.

Thanks
