### ISSUE TITLE
Ability to Disable logging of "Getting Current Status", to stop spam the homebridge log

### ISSUE THREAD

**Issue by palletodap** [ptz0n/homebridge-verisure#93]
Hi,
Would it be possible to make a setting to disable the logging when the plugin is getting current status of devices from Verisure servers?

Its spamming a lot when you try to debug any other plugin through the log. 

Would be awesome with a disable setting 👍

**Comment by ptz0n** [comment]
You could simply filter out the rows from the plugin you are looking for. Personally I manage and rotate my logs using PM2. Spammy logs are awesome when you eventually try to resolve an issue.

Sorry, for now, I will not implement an option for disabling logs.

**Comment by palletodap** [comment]
Is pm2 available for the many users using HOOBS?

**Comment by ptz0n** [comment]
I'm not sure, but it seems that they have some kind of log rotation built in 👍

**Comment by DennisJohnsen** [comment]
Sorry for opening up old wounds, but is it possible to reconsider this, as there is a lot of us that uses the Homebridge UI logs only, and the other plugins that I use have options to enable debug logging, or keeping it minimal.

What if an option for not logging anything unless there is an error or an state has changed?

**Comment by ptz0n** [comment]
You are right. The logs are quite verbose today. I agree that the log statements based from polling could be lowered to debug.

**Comment by dewoert** [comment]
Is there any progress on this ?
I would like to be able to disable the "info" log entrys
Perhaps there is an easy manual fix by modifying one of the plugin files ?

**Comment by ptz0n** [comment]
PR is out, please try it out.
