### ISSUE TITLE
Hiding auto-lock switch in homekit

### ISSUE THREAD

**Issue by vegargrim** [ptz0n/homebridge-verisure#94]
Hello

Is there a command for removing the auto-lock switch in homekit completely? 

Thanks for a great plugin!

**Comment by ptz0n** [comment]
No, there isn't such an option. Can I ask why you would want to?

Proposed solution: Remove the accessory from your favorites and move to a room way off to the right.

**Comment by vegargrim** [comment]
I have auto lock on by default and rarely use it. I have moved it in a room far to the right. If I need to use it I usually use the verisure app. The reason I want it removed from homekit completely is because I use «turn off everything» command with siri often. This will also turn off auto lock since autolock on, is switch on in homekit.

Best regards

**Comment by ptz0n** [comment]
I understand and agree that this would be a desired feature of this plugin. Will keep this issue open until resolved.

**Comment by zeekens** [comment]
Seconded, I'd like this option as well

**Comment by albinmedoc** [comment]
I agree. Adding an option to hide this switch would be great.
