### ISSUE TITLE
Plugin takes Homebridge Offline

### ISSUE THREAD

**Issue by GoTeslaGo** [ptz0n/homebridge-verisure#95]
Have tried to set this up using both my email address and my username for the Verisure app/website and neither works. In all instances it fails and prevents Homebridge from actually starting. The HB logs show:

Failed to initialize HTTPError: Response code 500 (Error Interno del Servidor)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure-stv/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'HTTPError',
  code: undefined,
  timings: {
    start: 1605176963037,
    socket: 1605176963037,
    lookup: 1605176963038,
    connect: 1605176963076,
    secureConnect: 1605176963115,
    upload: 1605176963115,
    response: 1605176963425,
    end: 1605176963426,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 38,
      tls: 39,
      request: 0,
      firstByte: 310,
      download: 1,
      total: 389

Now its showing this error but still not letting me start Homebridge until i uninstall the plugin:

[verisure] Error: <response><status><errorGroup>UNAUTHORIZED</errorGroup><errorCode>AUT_00008</errorCode><errorMessage>**User has been blacklisted due to subsequent failed attempts**</errorMessage></status></response>
    at /usr/local/lib/node_modules/homebridge-verisure/lib/platform.js:89:72
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:71750) UnhandledPromiseRejectionWarning: TypeError: accessories.forEach is not a function
    at /usr/local/lib/node_modules/homebridge/src/server.ts:417:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at /usr/local/lib/node_modules/homebridge-verisure/lib/platform.js:102:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:71750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:71750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ptz0n** [comment]
It appears that you are not using the module originated from this repository. Instead you are using: `homebridge-verisure-stv` which is a different module.

Please reach out to the developer of that module for support.

Just curious; in which country is your Verisure installation located?

**Comment by GoTeslaGo** [comment]
Apologies ptz0n i was trying multiple plugins as none were working. I am based in the UK.

Have reinstalled yours and provided my email and password but its being rejected:

 [verisure] Error: <response><status><errorGroup>UNAUTHORIZED</errorGroup><errorCode>AUT_00001</errorCode><errorMessage>Username/password does not match any valid login</errorMessage></status></response>
    at /usr/local/lib/node_modules/homebridge-verisure/lib/platform.js:89:72
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I also tried my username which is what i actually use to log into the Verisure app and website but getting the same error

**Comment by GoTeslaGo** [comment]
Apologies ptz0n i was trying multiple plugins as none were working. I am based in the UK.

Have reinstalled yours and provided my email and password but its being rejected:

 [verisure] Error: <response><status><errorGroup>UNAUTHORIZED</errorGroup><errorCode>AUT_00001</errorCode><errorMessage>Username/password does not match any valid login</errorMessage></status></response>
    at /usr/local/lib/node_modules/homebridge-verisure/lib/platform.js:89:72
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I also tried my username which is what i actually use to log into the Verisure app and website but getting the same error

**Comment by ptz0n** [comment]
No worries. For installations in the UK, you should use a plugin that's compatible with the Securitas Direct API.

The plugin `homebridge-verisure-stv` seem to be working for you.

I'm working on releasing a new plugin with support for Securitas Direct installations. See: https://github.com/ptz0n/homebridge-verisure/issues/80

**Comment by GoTeslaGo** [comment]
great thanks. However the STV isn't working and theres a lack of documentation on how to set it up:

[Verisure] Failed to set status to 3 MaxRedirectsError: Redirected 10 times. Aborting.
    at Request._onResponseBase (/usr/local/lib/node_modules/homebridge-verisure-stv/node_modules/got/dist/source/core/index.js:850:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Request._onResponse (/usr/local/lib/node_modules/homebridge-verisure-stv/node_modules/got/dist/source/core/index.js:931:13) {
  name: 'MaxRedirectsError',
  code: undefined,
  timings: undefined
}

**Comment by ptz0n** [comment]
Hold on tight, I'm spending a few hours to setup a working integration.

**Comment by GoTeslaGo** [comment]
Any luck with this?

**Comment by ptz0n** [comment]
Making progress. Will be ready for testing in a few days.

**Comment by GoTeslaGo** [comment]
Great job! I’m happy to help testing

**Comment by artik** [comment]
@ptz0n Erik, you mean Securitas plugin will be available in few days ? Will be my best Christmas present :)

**Comment by ptz0n** [comment]
Yes, testing it out as I'm writing this.

**Comment by ptz0n** [comment]
Plugin published, please help out with testing: https://github.com/ptz0n/homebridge-securitas-direct

**Comment by GoTeslaGo** [comment]
downloaded and running now. Its connected but haven't tested arming and disarming yet as am at home but will try this later.

You mention being able to use variables to store username/password...how do I do this so as not to expose my details in the config.json?

**Comment by ptz0n** [comment]
@GoTeslaGo Great! Please create an issue in the other repository if you find any.

The environment variable feature was introduced to be used with Docker containers, see: https://github.com/ptz0n/homebridge-verisure/issues/47. But it's really up to you where you wanna put your secrets and how you choose to protect them.

How to set environment variables depends on how you're running Homebridge. Why do you feel that your secrets in `config.json` are exposed?
