### ISSUE TITLE
Where to set environment variable

### ISSUE THREAD

**Issue by vu-mai** [ptz0n/homebridge-verisure#97]
I've seen the implementation of using environment variables for password etc, but where do you guys set these environment variables in raspberry pi? I've tried creating .env-file in `/var/lib/homebridge`, adding env var into `.bashrc` and `.bash_profile`, but still homebridge can't seem to be reading them. Any ideas?

**Comment by ptz0n** [comment]
It depends on how you are starting homebridge. Are you using any process manager like PM2 or nodemon?

**Comment by vu-mai** [comment]
The only thing I did was flashing my sd card with Homebridge Raspberry Pi Image via Etcher and it started up automatically.

**Comment by vu-mai** [comment]
According to https://github.com/homebridge/homebridge-raspbian-image#configuration-reference, the systemd env file is actually in `/etc/default/homebridge` which resolved this issue :)
